<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'name' => '管理者',
                'kana' => 'カンリシャ',
                'search' => '管理者(カンリシャ)',
                'tel' => '0956478861',
                'email' => 'manager@email.com',
                'role' => 1,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => 'テストユーザー1',
                'kana' => 'テストユーザー1',
                'search' => 'テストユーザー1(テストユーザー1)',
                'tel' => '08012345678',
                'email' => 'customer001@email.com',
                'role' => 0,
                'password' => '$2y$10$drjeaLhzJN7Y/c4RGX2H0uB.Qz.SyA2O76ko4jlxfdaZ98ZOg2Bk6',
            ],
            [
                'name' => 'テストユーザー2',
                'kana' => 'テストユーザー2',
                'search' => 'テストユーザー2(テストユーザー2)',
                'tel' => '08012345678',
                'email' => 'customer002@email.com',
                'role' => 0,
                'password' => '$2y$10$drjeaLhzJN7Y/c4RGX2H0uB.Qz.SyA2O76ko4jlxfdaZ98ZOg2Bk6',
            ],
            [
                'name' => '川島永嗣',
                'kana' => 'カワシマエイジ',
                'search' => '川島永嗣(カワシマエイジ)',
                'tel' => '00000000000',
                'email' => 'kawashima@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '権田修一',
                'kana' => 'ゴンダシュウイチ',
                'search' => '権田修一(ゴンダシュウイチ)',
                'tel' => '00000000000',
                'email' => 'gonda@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '長友佑都',
                'kana' => 'ナガトモユウト',
                'search' => '長友佑都(ナガトモユウト)',
                'tel' => '00000000000',
                'email' => 'nagatomo@email.com',
                'role' => 0,
                'password' => '$2y$10$RZ3OrLLakQo3jZYONb7mZuK.AFdOK878McdG01DmZKssEGYCNsNuS',
            ],
            [
                'name' => '吉田麻也',
                'kana' => 'ヨシダマヤ',
                'search' => '吉田麻也(ヨシダマヤ)',
                'tel' => '00000000000',
                'email' => 'yoshida@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '酒井宏樹',
                'kana' => 'サカイヒロキ',
                'search' => '酒井宏樹(サカイヒロキ)',
                'tel' => '00000000000',
                'email' => 'sakai@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '谷口彰悟',
                'kana' => 'タニグチショウゴ',
                'search' => '谷口彰悟(タニグチショウゴ)',
                'tel' => '00000000000',
                'email' => 'taniguchi@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '柴崎岳',
                'kana' => 'シバサキガク',
                'search' => '柴崎岳(シバサキガク)',
                'tel' => '00000000000',
                'email' => 'shibasaki@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '遠藤航',
                'kana' => 'エンドウワタル',
                'search' => '遠藤航(エンドウワタル)',
                'tel' => '00000000000',
                'email' => 'endo@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '伊藤純也',
                'kana' => 'イトウジュンヤ',
                'search' => '伊藤純也(イトウジュンヤ)',
                'tel' => '00000000000',
                'email' => 'ito@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '山根視来',
                'kana' => 'ヤマネミキ',
                'search' => '山根視来(ヤマネミキ)',
                'tel' => '00000000000',
                'email' => 'yamane@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '浅野琢磨',
                'kana' => 'アサノタクマ',
                'search' => '浅野琢磨(アサノタクマ)',
                'tel' => '00000000000',
                'email' => 'asano@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '南野拓実',
                'kana' => 'ミナミノタクミ',
                'search' => '南野拓実(ミナミノタクミ)',
                'tel' => '00000000000',
                'email' => 'minamino@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '守田英正',
                'kana' => 'モリタヒデマサ',
                'search' => '守田英正(モリタヒデマサ)',
                'tel' => '00000000000',
                'email' => 'morita@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '鎌田大地',
                'kana' => 'カマダダイチ',
                'search' => '鎌田大地(カマダダイチ)',
                'tel' => '00000000000',
                'email' => 'kamada@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '板倉滉',
                'kana' => 'イタクラコウ',
                'search' => '板倉滉(イタクラコウ)',
                'tel' => '00000000000',
                'email' => 'itakura@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '町野修斗',
                'kana' => 'マチノシュウト',
                'search' => '町野修斗()',
                'tel' => '00000000000',
                'email' => 'machino@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '相馬勇紀',
                'kana' => 'ソウマユウキ',
                'search' => '相馬勇紀(ソウマユウキ)',
                'tel' => '00000000000',
                'email' => 'soma@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '三苫薫',
                'kana' => 'ミトマカオル',
                'search' => '三苫薫(ミトマカオル)',
                'tel' => '00000000000',
                'email' => 'mitoma@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '前田大然',
                'kana' => 'マエダダイゼン',
                'search' => '前田大然(マエダダイゼン)',
                'tel' => '00000000000',
                'email' => 'maeda@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '堂安律',
                'kana' => 'ドウアンリツ',
                'search' => '堂安律(ドウアンリツ)',
                'tel' => '00000000000',
                'email' => 'doan@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '上田綺世',
                'kana' => 'ウエダアヤセ',
                'search' => '上田綺世(ウエダアヤセ)',
                'tel' => '00000000000',
                'email' => 'ueda@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '田中碧',
                'kana' => 'タナカアオ',
                'search' => '田中碧(タナカアオ)',
                'tel' => '00000000000',
                'email' => 'tanaka@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '冨安健洋',
                'kana' => 'トミヤスタケヒロ',
                'search' => '冨安健洋(トミヤスタケヒロ)',
                'tel' => '00000000000',
                'email' => 'tomiyasu@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '久保建英',
                'kana' => 'クボタケフサ',
                'search' => '久保建英(クボタケフサ)',
                'tel' => '00000000000',
                'email' => 'kubo@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => 'シュミットダニエル',
                'kana' => 'シュミットダニエル',
                'search' => 'シュミットダニエル(シュミットダニエル)',
                'tel' => '00000000000',
                'email' => 'schmidt@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '本田圭佑',
                'kana' => 'ホンダケイスケ',
                'search' => '本田圭佑(ホンダケイスケ)',
                'tel' => '00000000000',
                'email' => 'honda@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '中田英寿',
                'kana' => 'ナカタヒデトシ',
                'search' => '中田英寿(ナカタヒデトシ)',
                'tel' => '00000000000',
                'email' => 'nakata@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
            [
                'name' => '高原直泰',
                'kana' => 'タカハラナオヒロ',
                'search' => '高原直泰(タカハラナオヒロ)',
                'tel' => '00000000000',
                'email' => 'takahara@email.com',
                'role' => 0,
                'password' => '$2y$10$PdjkdUU3Mix97soyiTG1QOsiPcOgiXCL/X70pD2C4ofuFqTgntT22',
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert([
                'name' => $user['name'],
                'kana' => $user['kana'],
                'search' => $user['search'],
                'tel' => $user['tel'],
                'email' => $user['email'],
                'role' => $user['role'],
                'password' => $user['password'],
            ]);
        }
    }
}
